### ISSUE TITLE
Fix readme.md

### ISSUE THREAD

**Issue by tapchik** [pashcash/SimpleWikiMaker#25]
Are you sure you start your project with `./mvnw spring-boot:run`? Because I start my project with `mvn spring-boot:run`... 

If you too, I propose to replace current command to start a project with `mvn spring-boot:run`.

**Comment by pashcash** [comment]
Не получается запустить с помощью `mvn spring-boot:run`, оставлю как есть

**Comment by tapchik** [comment]
Command is system based then. You are running Windows and I am running MacOs. That explains it.
